#!/bin/bash
: 'This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
	
	Copyright (C) 2012 gymka <gymka at archlinux.lt>
	Paremta TeoBigusGeekus kodu.'
kelias=/home/gymka/Dev/conky_orai_LT
miestas="Kaunas"

if [[ "$miestas" == "Vilnius" ]]
then
	addr_now="http://www.weather.com/weather/right-now/Vilnius+LHXX0005:1:LH"
elif [[ "$miestas" == "Klaipėda" ]]
then
	addr_now="http://www.weather.com/weather/right-now/Klaipeda+LHXX0008:1:LH"
elif [[ "$miestas" == "Šiauliai" ]]
then
	addr_now="http://www.weather.com/weather/right-now/Siauliai+LHXX0009:1:LH"
elif [[ "$miestas" == "Panevėžys" ]]
then
	addr_now="http://www.weather.com/weather/right-now/Panevezys+LHXX0007:1:LH"
else 
	addr_now="http://www.weather.com/weather/right-now/Kaunas+LHXX0002:1:LH"
fi
mv $kelias/raw_rn $kelias/raw_rn_senas

kill -STOP $(pidof conky)
wget --user-agent="Firefox" --load-cookies $kelias/cookie -O $kelias/raw_rn $addr_now

size=$(stat -c%s $kelias/raw_rn) #jei dydis 0, kilo bėdų ir prognozė negauta, todėl reik naudot prieš tai buvusią prognozę
if [[ $size -eq '0' ]]; then
	rm $kelias/raw_rn
	mv $kelias/raw_rn_senas $kelias/raw_rn
else 
	if [[ -s $kelias/raw_rn ]]; then
		#############
		# Right now #
		#############
	laikas12=$(grep -o 'updated">.*Local Time' $kelias/raw_rn|sed  -e '1s/.*2012, \(.*\)Local.*/\1/' -e '2d')
	laikas24=$(date -d $laikas12 +%H:%M)

	
		sed -i '/wx-weather-icon wx-hide/,/<div class="wx-next6hr-details ">/!d' $kelias/raw_rn
		sed -i -e '/^[ \t]*$/d' -e 's/\r//g' $kelias/raw_rn
		sed -i '/\.png\|&deg;\|weather-phrase\|feels-like\|"wx-temp"\|"wx-value"\|arrow wind-dir-/!d' $kelias/raw_rn
		sed -i -e 's/^.*wxicon\/120\///g' -e s'/png.*$/png/g' -e 's/^.*"wx-temp">//g' $kelias/raw_rn
		sed -i -e 's/^.*wx-dir-arrow wind-dir-//g' -e 's/"><\/div>.*$//g' -e 's/<\/span>.*$//g' -e 's/^.*">//g' -e 's/&deg;//g' $kelias/raw_rn
		image=$(sed -n 1p $kelias/raw_rn)
		if [[ $(sed -n 6p $kelias/raw_rn) == "Calm" ]]; then
			sed -i '6s/$/\n/' $kelias/raw_rn
		fi
		#vejas turi but metrais per sekunde, o ne kilometrais per valanda
		vejas_km=$(sed -n 7p $kelias/raw_rn)
		vejas_m=$(echo "scale=2; $vejas_km/3.6" | bc)
		sed -i "7s/.*/$vejas_m/"	$kelias/raw_rn
		sed -i "14s/.*/$laikas24/"	$kelias/raw_rn

	    cp $kelias/piktogramos/$image $kelias/now.png
	fi
fi

$kelias/isverst_ora.sh
kill -CONT $(pidof conky)
